title: Sangeet Naryan!
description: Sangeet Narayan's Personal Website
author: Sangeet
github: https://github.com/sangeetds
disqus_shortname: sangeet-narayan
google_analytics: UA-XXXXXXXX-Y

author: Sangeet Narayan  # add your name
author-img: 65168994.jpg # add your photo
about-author: I'm the one who codes # add description
social-github: sangeetds # add your Github handle
social-linkedin: sangeetnarayan # add your Linkedin handle
social-email: sangeetnarayands@gmail.com # add your Email address

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

enableTags: true
tagarray: []

utterances:
  repo: "sangeetds/sangeetds.github.io"
  issue-term: "pathname"
  label: "utteranc.es"
  theme: "github-light"

# Disqus
discus-identifier: sangeet_narayan # add your discus identifier

collections:
  project:
    output: true
    permalink: /project/:path/

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Articles
      url: /articles
    - text: My Projects
      url: /projects/

url: "https://sangeetnarayan.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
